session_name: neovim-config
start_directory: ./
windows:
  - panes:
    - nvim
  - panes:
    - null
  - panes:
    - null
  - panes:
    - null
  - panes:
    - null
  - panes:
    - null
  - panes:
    - null
  - panes:
    - null
  - panes:
    - null
  - panes:
    - null
